FROM osixia/openldap
ENV LDAP_ORGANISATION {{dc_name1}}
ENV LDAP_DOMAIN {{dc_name1}}.{{dc_name2}}
ENV LDAP_BASE_DN cn=admin,dc={{dc_name1}},dc={{dc_name2}}
ENV LDAP_ADMIN_PASSWORD {{password}}
ENV LDAP_CONFIG_PASSWORD {{password}}
