---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: docker_restart_on_package_change

- include_tasks: docker-users.yml
  when: docker_users

- name: Copy Docker file
  template:
     src: Dockerfile.j2
     dest: /tmp/Dockerfile

- name: Create Docker image
  become_user: root
  command: docker build -t ldap:latest /tmp/

- name: Run LDAP container
  become_user: root
  command: docker run -d -p 389:389 ldap:latest
